[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "39ce31a57e2ccf78658abc7db0cde84d44cc1b0b"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "de36496d36f3ed2cc2af8d1fcbea7ce4421b633a1bd2c212e6b208273a2f0de2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.aarch64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "14efc049811a6ea44fd675924f3d81f72944e555"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "bdd1b7d8e885122afdc83ef45c8ddd85620de2926ebff96aa4e0f1a0914c5c1b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.aarch64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "0c0ae92e7f12e3fa1e881b8d6d90e88c5f730b53"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "4d0db487d690ede78e4628318b3ca658a7ce5260b3f0e86adfaf6109a7c19bf5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.aarch64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "451ce9e4573d371d71c0da9ed7374c440c643dcd"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "3766c49deb6fe99a4313953f0c0b7deb99eda341c8395bcebb8a44ac47316a32"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ff89add0ff8b399356303458347f3b4944fec6e"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "b4472ca4011923223791a8dd4afcc3b2e76e843536f53a391e66ddd01860662e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39d99154b44065d10b68dfc5972116dcdc3d8cfe"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "245f791c2068603aa304c839239f9f4c540a0cf0aa8f72bc2f2b8601cf3a6e1b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "108bfbeeca068de06c6501134ff2d6e6c01f120b"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "9e9c52711361b3d629fc9d25d7e17c0ce3d6e98d75a2c26c1189b77aea89fe55"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b36c2412dd97b0294cbb83b8974f7dfe8b7bb19c"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "70cc7a25150c0a96a4f80fff4257d84d2118d3d5a230658688ee626aa513c5ba"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "7673f534ffb83f5c29d90d0e246a1a87b8b8b343"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "9a469bfa7e7d5edf27a849c197e0593b408f04ed64fdb7e42b73b8c721a3fdec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.i686-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "ac854d8c5b11cf50ca2499f9faf85ba539c1c92a"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "ed2c6f12958c372fb28a47347ccf209c88658e6176e036eb02efe0b8772479a2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.i686-linux-musl.tar.gz"
[[aws_c_io]]
arch = "powerpc64le"
git-tree-sha1 = "6334312c091e897d8248365a668d5aa27b9b5adb"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "b6cb420b87531de5e76f8d4e27f9c5b4c0d1956cdbd78948235ba86f3e3d1874"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "riscv64"
git-tree-sha1 = "5532c79cb4129ff305b0a216f99a98182f4884f7"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "26edd7865e013fe956b67b86743168cf4e4c3d5049961445192c58480e0f31c0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.riscv64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "5f846563f3405744e46d75da2c3d06b5a1006f86"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "3dff99cdbf41bf458d1a0e7526c55f75694e4ca6eeeec6d2da88c3e630979c2d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.x86_64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "04ecbcbf785c36a6073bd055ef93d1fd3716ab71"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "b9fe4f1646f8f7c92b08b92c3771d365342cc201006e4fafe4efd1363fa1c474"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.x86_64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "9f52ed52d9e440f4dc58899c73483abb5d1f805a"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "3eef7bdc3190e60c965aba5a61292e9954be74c5ebe2e6b78d61396a4883fd66"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.x86_64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "9170d7f368e1e10a342358c367dcec2f0542477d"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "1aec97e659c28814b091fb39f991bb8e86179b13ce21cf01e99f439115ac6346"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "c140423a8b6f19de67f228ac368dcf85178954a4"
os = "windows"

    [[aws_c_io.download]]
    sha256 = "adcfe0426d9d099eab736555ec7657175965d98941c873f53d7d35d9151f3ee8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.1+0/aws_c_io.v0.26.1.x86_64-w64-mingw32.tar.gz"
