[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "088dda337b5dd334b2281a6365908a2514b60c08"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "f3297a118881b5a7801cf8205d17513de06245e746c04fe77b99813fc65ef42c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.aarch64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "9a958b10aa3ed9f8022b6c0abd6f26cf0946f7bb"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "cf0ca833a19f3bd9c637506caf1858303ec1dadddbace9ba018de9c32e2a8e17"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.aarch64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "a4166e9bddb2936df2e9b91ceea173a0bfc57424"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "48bb525ba81f491fbffe17d184cc9b1771891ab3256a75274f7abadd4108cb11"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.aarch64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "22f2594ee66e2494de7a34ecb289b6d6bebabc58"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "7669fbe9679e3a9fe17dc307c3fbf1bd161e8b8ce4e01a2b20569f194b054b72"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b0a887e84a05709e828095c20f3dfba309f2dab"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "e917936a4b170fd67d6a6c6083e49e75fbef442e9bd84fdccac3250d166f26e9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b382fad12dc20ab2ed03cceaf809bf4e1c77589"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "1fa254dfb6ecc3358432f3685208ef3e99bf35792f639b099b677798c9171656"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41b2ab29c1f26aa7a18bbcfa990b649fbaa67f06"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "1f123846f0bd2dd9cfd6744141f149ca590ea5a6fc630768c250350c142584e4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "117336fde5b9bff95e91c0b21dfd002077d83e90"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "47568e2cebc292503d59c215b8f079359fecee01df21fbad70c8c701cd856830"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "8b7bedb98ebd531e8e651957ab1e04937c9686ab"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "7be87037c5049c01058977d17666279e7c4d3a7d57847d2f6716bd354220f03d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.i686-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "66a7ecca8353e18269de121280484bafad631232"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "a7d320df7436996c02176938f5f90379e2cff2f9fb6ffefb3e2be610d3af9778"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.i686-linux-musl.tar.gz"
[[aws_c_io]]
arch = "powerpc64le"
git-tree-sha1 = "be611eeab15f5ef76247791c13a2aea3009ae37f"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "87e184d6df1c65a58fa1a8d9090cebfa677d5d8c93b32db95ce7cf10b9edd1c1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "riscv64"
git-tree-sha1 = "a56293aa8e0ae32f0dfbe7c8cc9db33eb2e95ef1"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "b59beeec977262e4c3dbc36cf90b467c165215869917929e5b1a8e1610e0c846"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.riscv64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "ada6c104a49e1cddd84a6271f7b39005f392491d"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "679b13ef1967afe2fb7dc9709229f91e4d8c75159b82448d679ee1cf914f0d47"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.x86_64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "82a973472690ef60c64b6a435ae31693dac5147b"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "f49cdd31a420ed10397c030d4f8ab0b40cf20039fc6727470a2063e5d8a88b9f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.x86_64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "f6efb000cd77204f569ae00878e56275e6abe679"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "88309b04f21649865eb3d2f50ad691ed586d24a35bd2ff397d206b62736b1bc1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.x86_64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "05490f3a7afc72ba9daa233d95f78c2173ce6428"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "fb675c506040b6d7e26cc2b4d0cd4a92ebfdd545f97ee9207c1f51d5d9ee33fc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "3e9ca9a297567b57584780b6f8659353a93f0c98"
os = "windows"

    [[aws_c_io.download]]
    sha256 = "4f65d4e1463956b8c99306feb07b653582d98d562504b7f99791a50e467541f2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.3+0/aws_c_io.v0.23.3.x86_64-w64-mingw32.tar.gz"
