[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "08b51637cfa35b791e8952ffc030bfff7d28bed1"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "133a0a938f34d6bd5ec82873f284468155338cc30e35f7127113ff75c9f923d8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.aarch64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "0c4b47cf593862185e2a99d0f6ff3bacf73b0e00"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "a411d0ca188ea5d5e1a1074013abb65b5b67e1f1239c90137de2a2ea31a77161"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.aarch64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "2584ef490f1cb6063a3b512b3f90fd22b57ed24d"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "5b49f8c372c911bdc52885d909127b84dfd62361f7cf97008a49ad54f69a34f9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.aarch64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "4e35bc419bedbd2d1c0f39947ecd02c24c0c67f5"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "e80be48050c5b06aacf525796ee392c7bada6f12bba1e5a88c62c3782c91ee0e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a4b18d9ad5086e643bde4d4bab91344ce00ee04"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "6d5ddf4f15e5c3c5b8068bd50cb4b9694a3c9310bdba190ee4f1904255a52c86"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a22246c22f18c738161fbb45d80d22ff5d08de64"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "ac499848d9a7732b4e7b16125625bb6e8c32c6d78549108273debe8d1d6288d3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "449ec3df7bc012a7ba548f05cef2e455e2622221"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "bfef2229f58ef2515ac202dffb159a0be8f45266ae9f0530a7a18b200a553245"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "829ab8f08e5913bee001175df2916c4cc1dfa6b3"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "71fad532fdaf411b85aa1c36660be90c9559c3ddc7b64566ef962830103cdb2a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "9c4e5f75278bfb4305a74d96e8085bc4a1c3fbdc"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "e07c7e5029659a8064a6c7de6f045cef1dfe0a696cb2aba0739e1f715d456ded"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.i686-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "22a96818e0ec0c007ccc35f5a55285419b99a6d3"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "8d0bf4d61f987aefdcca9132c9d1f4ae286ce1d3857321cf3c28619bb3564333"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.i686-linux-musl.tar.gz"
[[aws_c_io]]
arch = "powerpc64le"
git-tree-sha1 = "ee7f0b01eafc8ec61c7f73253617ec741455f76f"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "f004b45ed33e8e500fd458439f5a013c8b7accca062812ce4924066caa7091a3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "riscv64"
git-tree-sha1 = "0ab9e017d86449c82711b68f3515ff92a5b6d203"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "ae587f144a09a72ceab99c3d477f7f2dfdd1fa65b377025bc9b77255aeb25b9a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.riscv64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "d7c13628f40f7b15c51f1f68dad8b43ff424e595"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "ce6394e6ebe7219be6d95ffb0b938e437024454350c9f2634e701cea1ffc96bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.x86_64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "19399398fb32e564bf6047a40b80c6289660ccc1"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "2dbc4dce12191a258deef26fe8921c2254da18a00157d445e5691ad4a07a0047"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.x86_64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "602b92a0e8a4ec942d09e58b79bc7d689413b0d1"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "7b83ffd2eaf0b70a507efd87702ab08d1922e020f39fa2752121049f6ff57653"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.x86_64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "e912d099a665dbe7b55ff1b85a0868017e733b74"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "a4d3e920e4cf5ab6dfa4e6d3daf290faa10f290cf8c24c03b4dbdb2e6a6ea30d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "3332635315c53ca34e3ee2fa1a24c638c33e4f73"
os = "windows"

    [[aws_c_io.download]]
    sha256 = "071b99e285b0389fcd5aeddad3756204dcc97736aec9dde35654e26a6a0d93cb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.23.4+0/aws_c_io.v0.23.4.x86_64-w64-mingw32.tar.gz"
