name = "aws_c_io_jll"
uuid = "13c41daa-f319-5298-b5eb-5754e0170d52"
version = "0.24.2+0"

[deps]
aws_c_cal_jll = "70f11efc-bab2-57f1-b0f3-22aad4e67c4b"
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
aws_c_common_jll = "73048d1d-b8c4-5092-a58d-866c5e8d1e50"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
s2n_tls_jll = "1.6.3"
aws_c_cal_jll = "0.9.13"
Libdl = "< 0.0.1, 1"
aws_c_common_jll = "0.12.6"
Artifacts = "< 0.0.1, 1"
